language: php
dist: trusty
php:
  - 7.2
sudo: false
cache:
  directories:
    - $HOME/.composer/cache
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS travis;'
before_script:
  - cp .env.testing .env
  - travis_retry composer install --no-interaction --no-suggest
  - php artisan key:generate
  - php artisan migrate --seed
script:
  - vendor/bin/phpunit --coverage-text --colors=never

#after_success:
#  only:
#    - development
#  - mkdir -p ~/.ssh
#  - echo $(echo $SSH_PRIVATE_KEY | base64 -d) > ~/.ssh/id_rsa
#  - chmod -R 400 ~/.ssh
#  - rsync -az --exclude=.git --exclude=vendor --exclude=tests -e "ssh -o StrictHostKeyChecking=no -l $SSH_USER" ./ $IP:$TFOLDER
#  - ssh -o StrictHostKeyChecking=no $SSH_USER@$IP "cd $TFOLDER && composer install --no-dev --optimize-autoloader; php artisan migrate:fresh --seed"